# Generated by Django 3.2.6 on 2021-09-23 03:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('attrs', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='media/portfolio')),
            ],
        ),
    ]
