# Generated by Django 3.2.6 on 2021-09-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='media/projects')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_picture', to='frontend.portfolio')),
            ],
        ),
    ]
