# Generated by Django 3.2.6 on 2021-09-23 04:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_projectimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='attrs',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
