# Generated by Django 3.2.6 on 2021-09-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_projectimages_responsive'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_type',
            field=models.CharField(default='Other', max_length=64),
        ),
    ]
