# Generated by Django 3.2.6 on 2021-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_contact_emaillists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_type',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Scripting', 'Scripting'), ('Other', 'Other')], default='Other', max_length=64),
        ),
    ]
